#!/usr/bin/env bash
# Install Nginx
apt-get -y update
apt-get install -y nginx

# Set the custom HTTP response header in Nginx configuration
sed -i "24i\ \tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes

systemctl restart nginx
