#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Set the custom HTTP response header in Nginx configuration
sed -i '/^\s*http {/a \        server_tokens off;\n\n        location / {\n            add_header X-Served-By $hostname;\n        }' /etc/nginx/nginx.conf

# Restart Nginx to apply the changes

systemctl restart nginx
